[pytest]
filterwarnings =
    ignore:.*deprecated - use 'set_name'.*:DeprecationWarning:httplib2\.auth
    ignore:.*deprecated - use 'leave_whitespace'.*:DeprecationWarning:httplib2\.auth
    ignore:.*deprecated - use 'set_parse_action'.*:DeprecationWarning:httplib2\.auth
    ignore:.*deprecated - use 'add_parse_action'.*:DeprecationWarning:httplib2\.auth
    ignore:.*deprecated - use 'DelimitedList'.*:DeprecationWarning:httplib2\.auth
