from __future__ import annotations

from fastapi import APIRouter, Depends
from fastapi.responses import HTMLResponse

from app.core.security import load_tenant_features, require_feature
from app.web.tenant import views

router = APIRouter(prefix="/t", dependencies=[Depends(load_tenant_features)])

router.add_api_route(
    "/dashboard",
    views.dashboard,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("dashboard"))],
)
router.add_api_route(
    "/consultorios",
    views.consultorios_list,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("consultorios"))],
)
router.add_api_route(
    "/consultorios/new",
    views.consultorios_new_get,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("consultorios"))],
)
router.add_api_route(
    "/consultorios/new",
    views.consultorios_new_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("consultorios"))],
)
router.add_api_route(
    "/consultorios/{consultorio_id}/edit",
    views.consultorios_edit_get,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("consultorios"))],
)
router.add_api_route(
    "/consultorios/{consultorio_id}/edit",
    views.consultorios_edit_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("consultorios"))],
)
router.add_api_route(
    "/consultorios/{consultorio_id}/test-provider",
    views.consultorio_provider_test,
    methods=["POST"],
    dependencies=[Depends(require_feature("consultorios"))],
)
router.add_api_route(
    "/consultorios/{consultorio_id}/delete",
    views.consultorios_delete,
    methods=["POST"],
    dependencies=[Depends(require_feature("consultorios"))],
)

router.add_api_route(
    "/pacientes",
    views.pacientes_list,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("pacientes"))],
)
router.add_api_route(
    "/pacientes/new",
    views.pacientes_new_get,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("pacientes"))],
)
router.add_api_route(
    "/pacientes/new",
    views.pacientes_new_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("pacientes"))],
)
router.add_api_route(
    "/pacientes/{paciente_id}/edit",
    views.pacientes_edit_get,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("pacientes"))],
)
router.add_api_route(
    "/pacientes/{paciente_id}/edit",
    views.pacientes_edit_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("pacientes"))],
)
router.add_api_route(
    "/pacientes/{paciente_id}/delete",
    views.pacientes_delete,
    methods=["POST"],
    dependencies=[Depends(require_feature("pacientes"))],
)

router.add_api_route(
    "/turnos",
    views.turnos_list,
    methods=["GET"],
    dependencies=[Depends(require_feature("appointments"))],
)
router.add_api_route(
    "/turnos/{turno_id}",
    views.turnos_detail,
    methods=["GET"],
    dependencies=[Depends(require_feature("appointments"))],
)
router.add_api_route(
    "/appointments",
    views.appointments_list,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("appointments"))],
)
router.add_api_route(
    "/appointments/{turno_id}",
    views.appointment_detail,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("appointments"))],
)
router.add_api_route(
    "/appointments/{turno_id}/cancel",
    views.appointment_cancel,
    methods=["POST"],
    dependencies=[Depends(require_feature("appointments"))],
)
router.add_api_route(
    "/appointments/{turno_id}/resend",
    views.appointment_resend,
    methods=["POST"],
    dependencies=[Depends(require_feature("appointments"))],
)
router.add_api_route(
    "/payments",
    views.payments_list,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("payments"))],
)
router.add_api_route(
    "/payments/{payment_id}",
    views.payment_detail,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("payments"))],
)

router.add_api_route(
    "/conversation-states",
    views.conversation_states,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("conversaciones"))],
)
router.add_api_route(
    "/conversation-states/{telefono}",
    views.conversation_state_detail,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("conversaciones"))],
)
router.add_api_route(
    "/conversation-states/history/{history_id}",
    views.conversation_history_detail,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("conversaciones"))],
)
router.add_api_route(
    "/conversation-states/{telefono}/resolve",
    views.conversation_state_resolve,
    methods=["POST"],
    dependencies=[Depends(require_feature("conversaciones"))],
)
router.add_api_route(
    "/conversation-states/{telefono}/review",
    views.conversation_state_review_update,
    methods=["POST"],
    dependencies=[Depends(require_feature("conversaciones"))],
)
router.add_api_route(
    "/audit-logs",
    views.audit_logs,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("audit_logs"))],
)
router.add_api_route(
    "/notifications",
    views.notifications_list,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("notifications"))],
)
router.add_api_route(
    "/notifications/{notification_id}/read",
    views.notifications_mark_read,
    methods=["POST"],
    dependencies=[Depends(require_feature("notifications"))],
)
router.add_api_route(
    "/settings",
    views.settings_get,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("settings"))],
)
router.add_api_route(
    "/settings",
    views.settings_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("settings"))],
)
router.add_api_route(
    "/settings/payments",
    views.payment_settings_get,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("settings_payments"))],
)
router.add_api_route(
    "/settings/payments",
    views.payment_settings_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("settings_payments"))],
)
router.add_api_route(
    "/settings/calendar",
    views.calendar_settings_get,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("settings_calendar"))],
)
router.add_api_route(
    "/settings/calendar",
    views.calendar_settings_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("settings_calendar"))],
)
router.add_api_route(
    "/settings/calendar/test",
    views.calendar_settings_test,
    methods=["GET"],
    dependencies=[Depends(require_feature("settings_calendar"))],
)
router.add_api_route(
    "/settings/notifications",
    views.notifications_settings,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("settings_notifications"))],
)
