from __future__ import annotations

from fastapi import APIRouter, Depends
from fastapi.responses import HTMLResponse

from app.core.security import load_tenant_features, require_feature
from app.web.tenant import views

router = APIRouter(prefix="/t", dependencies=[Depends(load_tenant_features)])

router.add_api_route(
    "/dashboard",
    views.dashboard,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("dashboard"))],
)
router.add_api_route(
    "/consultorios",
    views.consultorios_list,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("consultorios"))],
)
router.add_api_route(
    "/consultorios/new",
    views.consultorios_new_get,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("consultorios"))],
)
router.add_api_route(
    "/consultorios/new",
    views.consultorios_new_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("consultorios"))],
)
router.add_api_route(
    "/consultorios/{consultorio_id}/edit",
    views.consultorios_edit_get,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("consultorios"))],
)
router.add_api_route(
    "/consultorios/{consultorio_id}/edit",
    views.consultorios_edit_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("consultorios"))],
)
router.add_api_route(
    "/consultorios/{consultorio_id}/test-provider",
    views.consultorio_provider_test,
    methods=["POST"],
    dependencies=[Depends(require_feature("consultorios"))],
)
router.add_api_route(
    "/consultorios/{consultorio_id}/google-calendars",
    views.consultorio_google_calendars,
    methods=["POST"],
    dependencies=[Depends(require_feature("consultorios"))],
)
router.add_api_route(
    "/google-calendars",
    views.tenant_google_calendars,
    methods=["POST"],
    dependencies=[Depends(require_feature("consultorios"))],
)
router.add_api_route(
    "/consultorios/{consultorio_id}/calendar-slots",
    views.consultorio_calendar_slots_get,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("consultorios"))],
)
router.add_api_route(
    "/consultorios/{consultorio_id}/calendar-slots",
    views.consultorio_calendar_slots_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("consultorios"))],
)
router.add_api_route(
    "/consultorios/{consultorio_id}/delete",
    views.consultorios_delete,
    methods=["POST"],
    dependencies=[Depends(require_feature("consultorios"))],
)

router.add_api_route(
    "/pacientes",
    views.pacientes_list,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("pacientes"))],
)
router.add_api_route(
    "/pacientes/new",
    views.pacientes_new_get,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("pacientes"))],
)
router.add_api_route(
    "/pacientes/new",
    views.pacientes_new_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("pacientes"))],
)
router.add_api_route(
    "/pacientes/sync-consultorio-movil",
    views.pacientes_sync_consultorio_movil,
    methods=["POST"],
    dependencies=[Depends(require_feature("pacientes"))],
)
router.add_api_route(
    "/pacientes/import-csv",
    views.pacientes_import_csv,
    methods=["POST"],
    dependencies=[Depends(require_feature("pacientes"))],
)
router.add_api_route(
    "/pacientes/{paciente_id}/sync-consultorio-movil",
    views.pacientes_sync_one_consultorio_movil,
    methods=["POST"],
    dependencies=[Depends(require_feature("pacientes"))],
)
router.add_api_route(
    "/pacientes/{paciente_id}/edit",
    views.pacientes_edit_get,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("pacientes"))],
)
router.add_api_route(
    "/pacientes/{paciente_id}/edit",
    views.pacientes_edit_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("pacientes"))],
)
router.add_api_route(
    "/pacientes/{paciente_id}/delete",
    views.pacientes_delete,
    methods=["POST"],
    dependencies=[Depends(require_feature("pacientes"))],
)

router.add_api_route(
    "/turnos",
    views.turnos_list,
    methods=["GET"],
    dependencies=[Depends(require_feature("appointments"))],
)
router.add_api_route(
    "/turnos/{turno_id}",
    views.turnos_detail,
    methods=["GET"],
    dependencies=[Depends(require_feature("appointments"))],
)
router.add_api_route(
    "/appointments",
    views.appointments_list,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("appointments"))],
)
router.add_api_route(
    "/appointments/google/assign",
    views.appointment_google_assign,
    methods=["POST"],
    dependencies=[Depends(require_feature("appointments"))],
)
router.add_api_route(
    "/appointments/patients/search",
    views.appointment_patient_search,
    methods=["GET"],
    dependencies=[Depends(require_feature("appointments"))],
)
router.add_api_route(
    "/appointments/{turno_id}",
    views.appointment_detail,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("appointments"))],
)
router.add_api_route(
    "/appointments/{turno_id}/cancel",
    views.appointment_cancel,
    methods=["POST"],
    dependencies=[Depends(require_feature("appointments"))],
)
router.add_api_route(
    "/appointments/{turno_id}/resend",
    views.appointment_resend,
    methods=["POST"],
    dependencies=[Depends(require_feature("appointments"))],
)
router.add_api_route(
    "/payments",
    views.payments_list,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("payments"))],
)
router.add_api_route(
    "/payments/{payment_id}",
    views.payment_detail,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("payments"))],
)
router.add_api_route(
    "/billing-arca",
    views.billing_arca_list,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing",
    views.billing_arca_list,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing/invoices",
    views.billing_arca_list,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing-arca/items",
    views.billing_arca_items_list,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/settings/billing/items",
    views.billing_arca_items_list,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing-arca/items/new",
    views.billing_arca_item_new_get,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing-arca/items/new",
    views.billing_arca_item_new_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing-arca/{invoice_id}",
    views.billing_arca_detail,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing/invoices/{invoice_id}",
    views.billing_arca_detail,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing-arca/{invoice_id}/comprobante.html",
    views.billing_arca_invoice_html,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing-arca/{invoice_id}/comprobante.pdf",
    views.billing_arca_invoice_pdf,
    methods=["GET"],
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing-arca/{invoice_id}/send-email",
    views.billing_arca_send_email,
    methods=["POST"],
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing-arca/items/{item_id}/edit",
    views.billing_arca_item_edit_get,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/settings/billing/items/{item_id}/edit",
    views.billing_arca_item_edit_get,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing-arca/items/{item_id}/edit",
    views.billing_arca_item_edit_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/settings/billing/items/{item_id}/edit",
    views.billing_arca_item_edit_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing-arca/items/{item_id}/delete",
    views.billing_arca_item_delete,
    methods=["POST"],
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/settings/billing/items/{item_id}/delete",
    views.billing_arca_item_delete,
    methods=["POST"],
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing/pending",
    views.billing_pending_consultations,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing/pending/import",
    views.billing_pending_import,
    methods=["POST"],
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing/preview",
    views.billing_invoice_preview,
    methods=["POST"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing/emit",
    views.billing_invoice_emit_batch,
    methods=["POST"],
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing/emit/{consultation_id}",
    views.billing_invoice_emit_one,
    methods=["POST"],
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/billing/pending/{consultation_id}/diagnosis",
    views.billing_pending_diagnosis_update,
    methods=["POST"],
    dependencies=[Depends(require_feature("billing_arca"))],
)

router.add_api_route(
    "/conversation-states",
    views.conversation_states,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("conversaciones"))],
)
router.add_api_route(
    "/conversation-states/{telefono}",
    views.conversation_state_detail,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("conversaciones"))],
)
router.add_api_route(
    "/conversation-states/history/{history_id}",
    views.conversation_history_detail,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("conversaciones"))],
)
router.add_api_route(
    "/conversation-states/{telefono}/resolve",
    views.conversation_state_resolve,
    methods=["POST"],
    dependencies=[Depends(require_feature("conversaciones"))],
)
router.add_api_route(
    "/conversation-states/{telefono}/review",
    views.conversation_state_review_update,
    methods=["POST"],
    dependencies=[Depends(require_feature("conversaciones"))],
)
router.add_api_route(
    "/audit-logs",
    views.audit_logs,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("audit_logs"))],
)
router.add_api_route(
    "/notifications",
    views.notifications_list,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("notifications"))],
)
router.add_api_route(
    "/notifications/{notification_id}/read",
    views.notifications_mark_read,
    methods=["POST"],
    dependencies=[Depends(require_feature("notifications"))],
)
router.add_api_route(
    "/settings",
    views.settings_get,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("settings"))],
)
router.add_api_route(
    "/settings",
    views.settings_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("settings"))],
)
router.add_api_route(
    "/settings/payments",
    views.payment_settings_get,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("settings_payments"))],
)
router.add_api_route(
    "/settings/payments",
    views.payment_settings_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("settings_payments"))],
)
router.add_api_route(
    "/settings/calendar",
    views.calendar_settings_get,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("settings_calendar"))],
)
router.add_api_route(
    "/settings/calendar",
    views.calendar_settings_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("settings_calendar"))],
)
router.add_api_route(
    "/settings/calendar/test",
    views.calendar_settings_test,
    methods=["GET"],
    dependencies=[Depends(require_feature("settings_calendar"))],
)
router.add_api_route(
    "/settings/billing-arca",
    views.billing_arca_settings,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/settings/billing",
    views.billing_arca_settings,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/settings/billing-arca",
    views.billing_arca_settings_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/settings/billing",
    views.billing_arca_settings_post,
    methods=["POST"],
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/settings/billing-arca/test",
    views.billing_arca_settings_test,
    methods=["POST"],
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/settings/billing/test",
    views.billing_arca_settings_test,
    methods=["POST"],
    dependencies=[Depends(require_feature("billing_arca"))],
)
router.add_api_route(
    "/settings/notifications",
    views.notifications_settings,
    methods=["GET"],
    response_class=HTMLResponse,
    dependencies=[Depends(require_feature("settings_notifications"))],
)
